# Generated by Django 3.2.16 on 2023-02-25 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='complete',
        ),
    ]
